name: Build and Artifact the ESP-IDF Project

on:
  push:
    branches:
      - main     # ВАЖНО: Копим кэш в основной ветке, чтобы новые теги могли его прочитать
    tags:
      - 'v*'
  release:
    types: [published]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

concurrency:
  group: build-release-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build_for_esp32s3:
    name: Build binary for ESP32-S3
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # 1. Проверяем точный готовый файл для текущего тега (для сценария ПЕРЕСОЗДАНИЯ)
      - name: Cache Exact Final Binary
        id: cache-binary
        uses: actions/cache@v4
        with:
          path: build/ETCU.bin
          key: binary-${{ github.ref_name }}

      # 2. Кэш компилятора. Если точного .bin нет, берем базовый ccache из ветки main
      - name: Cache ccache compiler outputs
        if: steps.cache-binary.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt', '**/sdkconfig*', '**/main/idf_component.yml') }}
          # restore-keys заставит GitHub искать кэш в родительской ветке (main), если точный ключ не найден
          restore-keys: |
            ${{ runner.os }}-ccache-

      # 3. Сборка ESP-IDF
      - name: esp-idf build
        if: steps.cache-binary.outputs.cache-hit != 'true'
        uses: espressif/esp-idf-ci-action@v1
        env:
          IDF_CCACHE_ENABLE: "1"               # ВАЖНО: Включаем ccache внутри ESP-IDF
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_MAXSIZE: '500M'
        with:
          esp_idf_version: v6.1
          target: esp32s3
          path: '.'

      # 4. Загрузка в релиз (выполняется только если событие — это релиз или тег)
      - name: Upload binaries to release
        if: github.ref_type == 'tag' || github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ETCU.bin
          asset_name: etcu-esp32s3-${{ github.ref_name }}.bin
          tag: ${{ github.ref }}
          overwrite: true
